fix bisa

diff --git a/.github/workflows/CI-CD.yml b/.github/workflows/CI-CD.yml
--- a/.github/workflows/CI-CD.yml
+++ b/.github/workflows/CI-CD.yml
@@ -57,6 +57,21 @@ jobs:
           key: ${{ secrets.SSH_KEY }}
           script: |
             cd ~/
+
+            if ! command -v docker &> /dev/null
+            then
+              echo "Docker not found. Installing Docker..."
+              curl -fsSL https://get.docker.com -o get-docker.sh
+              sh get-docker.sh
+            fi
+
+            if ! docker compose version &> /dev/null
+            then
+              echo "Docker Compose not found. Installing plugin..."
+              sudo apt-get update -y
+              sudo apt-get install -y docker-compose-plugin
+            fi
+
             docker pull ${{ secrets.DOCKERHUB_USERNAME }}/express-api:latest
             docker compose down
             docker compose up -d
